### ISSUE TITLE
Plugin disables itself on startup

### ISSUE THREAD

**Issue by Spaex** [Iridium-Development/IridiumChunkBusters#3]
Hay I've just bought IridiumChunkBusters but get the following error on startup and the plugin disables: https://pastebin.com/5E68qrx6

Using Paper version git-Paper-553 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Have I missed any dependencies or smth?

**Comment by PeachesMLG** [comment]
Should be fixed in 1.0.1
